name: TurtleResetWorld
version: 1.0.0 
main: co.andrescol.mc.plugin.turtleresetworld.TurtleResetWorldPlugin
description: With this plugin you can reset automatically worlds
softdepend:
  - GriefPrevention
depend:
  - WorldEdit
author: xX_andrescol_Xx
api-version: 1.16 
website: none
commands:
  turtle: 
    description: Reset worlds
    permission-message: '[TurtleResetWorld] You do not have permission for this command'
    permission: turtleresetworld
    usage: Incorrect usage, try /turtle regen <World name | all>
permissions:
  turtleresetworld: {description: Allows to see the plugin info, default: op}
  turtleresetworld.regen: {description: Allows regen worlds, default: op}
  turtleresetworld.reload: {description: Allows to execute the reload subcommand, default: op}
  turtleresetworld.hooks: {description: Show the hooks list, default: op}

