name: TurtleResetWorld
version: 1.0.0 
main: co.andrescol.mc.plugin.turtleresetworld.TurtleResetWorldPlugin
description: With this plugin you can reset automatically worlds
softdepend:
  - GriefPrevention
author: [xX_andrescol_Xx]
api-version: 1.16 
website:
commands:
  turtle: 
    description: Reset worlds
    permission-message: '[TurtleResetWorld] You dont haver permission for this command'
    permission: turtleresetworld.info
    usage: Incorrect usage, try /turtle regen <World name | all>
permissions:
  turtleresetworld.info: {description: Allows to see the plugin info, default: op}
  turtleresetworld.regen: {description: Allows regen worlds, default: op}
  turtleresetworld.reload: {description: Allows to execute the reload subcommand, default: op}

